### How to create a list in Python

In [9]:
L=list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
type(L[0])

int

In [14]:
import array
L=list(range(10))
A=array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [16]:
type(array)

module

In [17]:
np.array([1,2,3,4,5], dtype='float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [25]:
np.array([range(i,i+2) for i in [2,4,6]])

array([[2, 3],
       [4, 5],
       [6, 7]])

In [26]:
np.array([range(i,i+5) for i in [1,3,5,7]])

array([[ 1,  2,  3,  4,  5],
       [ 3,  4,  5,  6,  7],
       [ 5,  6,  7,  8,  9],
       [ 7,  8,  9, 10, 11]])

In [29]:
np.full((3,4), 6.9)

array([[6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9]])

In [32]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

In [34]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
np.linspace(1, 2, 20)

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [45]:
x2=np.random.randint(10, size=(3,5))  #gives a array from no. 0-10 of dimension (3,5)
x2

array([[8, 8, 8, 7, 0],
       [5, 5, 8, 8, 5],
       [8, 5, 5, 4, 5]])

In [46]:
print(x2.size)

15


In [47]:
print(x2.dtype)

int32


### Array Sorting

In [2]:
import numpy as np

In [3]:
x=np.array([3,6,2,1,6])
np.sort(x)

array([1, 2, 3, 6, 6])

In [5]:
x.sort()
print(x)

[1 2 3 6 6]


In [6]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [13]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)


x[i]

[1 0 3 2 4]


array([1, 2, 3, 4, 5])

In [7]:
np.sort(X, axis=0)  #sorts each column

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [8]:
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

### Min, Max, Sum

In [3]:
import numpy as np

In [4]:
x=np.random.randint(10, size=(3,5))
x

array([[2, 5, 2, 0, 7],
       [5, 5, 2, 9, 3],
       [8, 4, 4, 1, 8]])

In [5]:
np.min(x), np.max(x) #gives the min n max value of array

(0, 9)

In [6]:
np.sum(x)

65

In [7]:
print(x.min(), x.max(), x.sum())

0 9 65


In [8]:
x.min(axis=0) #returns min value of each column

array([2, 4, 2, 0, 3])

In [9]:
x.min(axis=1) #returns min value of each row

array([0, 2, 1])

In [12]:
print("Max in each columns", x.max(axis=0))
print("Max in each rows", x.max(axis=1))

Max in columns [8 5 4 9 8]
Max in rows [7 9 8]


In [14]:
a=np.array([1,2,3,4])
b=np.array([7,6,8,9])
a+b

array([ 8,  8, 11, 13])

### Array Indexing

In [26]:
import numpy as np
rand=np.random.RandomState(42)
x=rand.randint(100, size=10)
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [27]:
[x[1],x[3]]

[92, 71]

In [28]:
ind=[1,3,4]  #aise indexing karni h to ind= likhna hamesha, nai to syntax error aata h
x[ind]

array([92, 71, 60])

In [37]:
X = np.arange(12).reshape((3,4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
row=np.array([0,1,2])
col=np.array([2,1,3])
X[row,col]

array([ 2,  5, 11])

In [2]:
import numpy as np
rand=np.random.RandomState(0)
x=rand.randint(100, size=10)
x

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87])

In [3]:
import numpy as np
rand=np.random.RandomState(0)
x=rand.randint(100, size=10)
x

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87])

### Structured array

In [3]:
import numpy as np

In [4]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [6]:
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [7]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [8]:
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [9]:
data[0]

('Alice', 25, 55.)

In [11]:
data['age']

array([25, 45, 37, 19])

### Boolean Arrays


In [14]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [15]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [20]:
np.sum((x > 5) & (x < 9))  #there are 3 values in the array between 5 and 9

3

In [21]:
# are all values in each row less than 8?
np.all(x < 8, axis=1)

array([ True, False,  True])